
--CCDS
INSERT INTO CCDS (CCD, CCD_NM) VALUES ('100', '테스트코드')
INSERT INTO CCDS (CCD, CCD_NM) VALUES ('101', '테스트코드2')

--CCDS_DTL
INSERT INTO CCDS_DTL (CCD_DTL, CCD, CCD_DTL_NM, CCD_DTL_DESCT, USE_YN) VALUES ('01', '100', '상세코드1', '100번의상세코드입니다.', 'Y')
INSERT INTO CCDS_DTL (CCD_DTL, CCD, CCD_DTL_NM, CCD_DTL_DESCT, USE_YN) VALUES ('01', '101', '상세코드', '101번의상세코드입니다.', 'N')


--PRCS
INSERT INTO PRCS VALUES ('TEST001', '세척', 'TEST1', '테스트');
INSERT INTO PRCS VALUES ('TEST002', '혼합', 'TEST1', '테스트');
INSERT INTO PRCS VALUES ('TEST003', '포장', 'TEST2', '테스트');
INSERT INTO PRCS VALUES ('TEST004', '가열', 'TEST2', '테스트');


INSERT INTO PRCS_FLOW VALUES (1, '100', '세척', 'TEST001');
INSERT INTO PRCS_FLOW VALUES (2, '100', '혼합', 'TEST002');
INSERT INTO PRCS_FLOW VALUES (3, '100', '포장', 'TEST003');
INSERT INTO PRCS_FLOW VALUES (1, '200', '세척', 'TEST001');
INSERT INTO PRCS_FLOW VALUES (2, '200', '가열', 'TEST004');
INSERT INTO PRCS_FLOW VALUES (3, '200', '포장', 'TEST003');

--EQM
INSERT INTO EQM VALUES ('test1','test1','test1','test1',sysdate,1,100,0,'Y','test1');
INSERT INTO EQM VALUES ('test2','test2','test2','test2',sysdate,1,100,0,'Y','test2');

--EQM_LINE
INSERT INTO EQM_LINE VALUES('test1', 1, 'test1', 'Y');
INSERT INTO EQM_LINE VALUES('test2', 1, 'test2', 'Y');
INSERT INTO EQM_LINE VALUES('test3', 1, 'test3', 'Y');
INSERT INTO EQM_LINE VALUES('test4', 1, 'test4', 'Y');
INSERT INTO EQM_LINE VALUES('test5', 1, 'test5', 'Y');